name: autofix.ci
on:
  pull_request:
  push:
permissions: { }
jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Format Frontend
        working-directory: frontend
        run: |
          bun install
          bunx prettier --write .

      - name: Format Backend
        working-directory: backend
        run: |
          bun install
          bunx prettier --write .

      - uses: autofix-ci/action@v1
        with:
          commit-message: "Apply Prettier format"